// import type { Metadata } from "next";

import Nav from '@/components/ui/Nav/Nav';

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function AdminLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Nav />
      <div>
          {children}
      </div>
    </>
  );
}
